### ISSUE TITLE
Get all USB-HID devices without specifying product id or vendor id?

### ISSUE THREAD

**Issue by xanmankey** [TobiasJacob/dartusbhid#1]
I was looking through the dart package repository for a way to interface with devices, and I came across this package. This is the first I've actually heard of the USB-HID, but it definitely seems like something worth looking into and learning about. I was just wondering if there was a way to fetch a list of the currently connected USB-HID devices WITHOUT specifying a product id or vendor id (two parameters the ```enumerateDevices``` function seems to require). 

Thanks for this wrapper!

**Comment by TobiasJacob** [comment]
Hey, thanks!

Yes, if you pass 0 for vendor and product ID, it will enumerate all devices! I'll add this to the readme.
