### ISSUE TITLE
Error while build on linux

### ISSUE THREAD

**Issue by iFrez** [TobiasJacob/dartusbhid#2]
Hello, i have error. Сould you help me please?

> flutter build linux --release
> 
> CMake Error:
>   Error evaluating generator expression:
> 
>     $<TARGET_FILE:hidapi>
> 
>   No target "hidapi"
> 
> 
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> Building Linux application...
> Unable to generate build files

**Comment by TobiasJacob** [comment]
Likely you forgot to initialize the submodules

git submodule init
git submodule update
